name: "Bors"
on:
  push:
    branches:
      - staging
      - trying
env:
  GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GH_PACKAGES }}
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:nix
      options: --privileged -v /dev:/dev -v /bin:/host/bin -v /lib/modules:/lib/modules
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: ln -s /host/bin/kmod /bin/modprobe
      - run: /bin/modprobe nbd
      - run: /bin/modprobe xfs
      - run: echo 1024 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: rm mayastor/.cargo/config
        # csi and cli crates are exec-ed within the tests
      - run: cargo build -p csi
      - run: cargo build -p cli
      - run: pushd jsonrpc && cargo test && popd
      - run: pushd mayastor && cargo test -- --test-threads=1 && popd
      - run: pushd mayastor-test && npm install && ./node_modules/mocha/bin/mocha test_cli.js && popd
      - run: pushd mayastor-test && ./node_modules/mocha/bin/mocha test_replica.js && popd
      - run: pushd mayastor-test && ./node_modules/mocha/bin/mocha test_csi.js && popd
      - run: pushd mayastor-test && ./node_modules/mocha/bin/mocha test_nexus.js && popd
      - run: pushd mayastor-test && ./node_modules/mocha/bin/mocha test_rebuild.js && popd
  Image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v7
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: nix-build -A mayastorImage -o /tmp/mayastorImage
      - run: nix-build -A node-moacImage -o /tmp/node-moacImage
  ms-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - run: nix-build -A ms-buildenv
