name: "build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: docker://mayadata/ms-buildenv:latest
      with:
        entrypoint: /bin/sh
        args: "-c \"nix-shell --run 'cargo build --all'\""