name: "build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: docker://mayadata/ms-buildenv:latest
    - run: nix-shell --run 'true'
