name: "CI-basic"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://mayadata/ms-buildenv:latest
        with:
          entrypoint: /bin/sh
          args: '-c \"nix-env -iA cachix -f https://cachix.org/api/v1/install && nix-shell --run ''cachix use mayastor && cargo build --all''\"'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://mayadata/ms-buildenv:latest
        with:
          entrypoint: /bin/sh
          args: '-c \"nix-env -iA cachix -f https://cachix.org/api/v1/install && nix-shell --run ''cachix use mayastor && cargo build --all''\"'
