on: push
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    container:
      image: mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
