name: "no bling-bling tests"
on:
  pull_request:
    paths-ignore:
  push:
    branches:
      #  - develop
jobs:
  nix-shell:
    name: check and see if it works
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: sudo modprobe nbd
      - run: sudo modprobe xfs
      - run: sudo modprobe nvme_tcp
      - run: echo 8192 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: nix-shell --run "echo 'Pulling in the environment...'"
      - run: nix-shell --run "./scripts/test.sh"
      - run: sudo rm -rf /tmp/*
      - run: sudo losetup -D
      # permissions are clashing with containers!!! should not be needed
      # after merge
      - run: sudo rm -rf "/home/gila/actions-runner/_work/Mayastor/Mayastor/.git"
  Build_and_test_moac:
    name: Build and run moac tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@v2
      # npm prepare is normally done by npm install but not if run as a root
      - run: cd csi/moac && npm install && npm run prepare && npm run compile
      - run: cd csi/moac && npm test
