name: "Lint and style Checks"
on:
  pull_request:
jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:nix
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          components: clippy
      - uses: actions-rs/clippy-check@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets -- -D warnings
  Prettier:
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:nix
    steps:
      - uses: actions/checkout@master
      - run: prettier --config .prettierrc --check csi/moac/*.js
      - run: prettier --config .prettierrc --check mayastor-test/*.js
      - run: jshint --config .jshintrc csi/moac/*.js mayastor-test/*.js
