name: rtest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://mayadata/ms-buildenv:nix
      options: --privileged -v /dev:/dev -v /bin:/host/bin -v /lib/modules:/lib/modules
    steps:
      - uses: actions/checkout@v2
      - name: Kernel Setup
        run: |
          ln -s /host/bin/kmod /bin/modprobe
          /bin/modprobe nbd; /bin/modprobe xfs
          # Allocate 1024 2MiB hugepages
          echo 1024 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages 1>/dev/null
      - name: rust tests
        run: |
          rustup default nightly
          rm mayastor/.cargo/config
          ./test.sh

